# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb06c3368284a19e00699f849583e0ddffcb76d845df32bbfaf15c8588e77c59c30962a6a5483a76a6322ac0f72524230c8bb3379b421b5a9811a992041bf425

test:
  secret_key_base: de325947f7a4bdbb03ab5ec28feb04784016923c883e5525cd35a276ceb8ca486065a9f91281c3d460f55ecfced03c5375fc9ceda5336cf388201340d5d0635d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
